#########
# MODEL
#########

# Encoder
ENCODER_OUTPUT_DIM = 256
ENCODER_DROPOUT = 0.2

# Attention
ATTENTION_HIDDEN_DIM = 256

# Decoder
DECODER_EMBEDDING_DIM = 256
DECODER_HIDDEN_DIM = 256
DECODER_DROPOUT = 0.3

# Deep output layer
DEEP_OUTPUT_DROPOUT = 0.2


############
# TRAINING
############

RANDOM_SEED = 42

BATCH_SIZE = 64
NUM_EPOCHS = 50

# Optimizer
LEARNING_RATE = 1e-3


############
# CALLBACKS
############

VAL_LOSS = "val_loss"
VERBOSE = 1
MIN = "min"

# ModelCheckpoint
CHECKPOINT_MONITOR = VAL_LOSS
CHECKPOINT_VERBOSE = VERBOSE
CHECKPOINT_SAVE_BEST_ONLY = True
CHECKPOINT_SAVE_WEIGHTS_ONLY = False
CHECKPOINT_MODE = MIN
CHECKPOINT_SAVE_FREQ = "epoch"

# ReduceLROnPlateau
REDUCE_LR_MONITOR = VAL_LOSS
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_PATIENCE = 2
REDUCE_LR_VERBOSE = VERBOSE
REDUCE_LR_MODE = MIN
REDUCE_LR_MIN_DELTA = 1e-4
REDUCE_LR_MIN_LR = 1e-5

# EarlyStopping
EARLY_STOPPING_MONITOR = VAL_LOSS
EARLY_STOPPING_MIN_DELTA = 1e-4
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_VERBOSE = VERBOSE
EARLY_STOPPING_MODE = MIN
EARLY_STOPPING_RESTORE_BEST_WEIGHTS = False
