#########
# MODEL
#########

# Attention
ATTENTION_HIDDEN_DIM = 256

# Decoder
DECODER_HIDDEN_DIM = 256

# Embedding
EMBEDDING_DIM = 256

# Encoder
ENCODER_OUTPUT_DIM = 256

# Dropout
DECODER_OUTPUT_DROPOUT = 0.3
EMBEDDING_OUTPUT_DROPOUT = 0.1

############
# TRAINING
############

VERBOSE = 1

RANDOM_SEED = 42

BATCH_SIZE = 64
NUM_EPOCHS = 50
TRAINING_VERBOSE = VERBOSE

# Optimizer
LEARNING_RATE = 1e-3

############
# CALLBACKS
############

VAL_LOSS = "val_loss"
MIN = "min"

# ModelCheckpoint
CHECKPOINT_MONITOR = VAL_LOSS
CHECKPOINT_VERBOSE = VERBOSE
CHECKPOINT_SAVE_BEST_ONLY = True
CHECKPOINT_SAVE_WEIGHTS_ONLY = False
CHECKPOINT_MODE = MIN
CHECKPOINT_SAVE_FREQ = "epoch"

# ReduceLROnPlateau
REDUCE_LR_MONITOR = VAL_LOSS
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_PATIENCE = 3
REDUCE_LR_VERBOSE = VERBOSE
REDUCE_LR_MODE = MIN
REDUCE_LR_MIN_DELTA = 1e-4
REDUCE_LR_MIN_LR = 1e-5

# EarlyStopping
EARLY_STOPPING_MONITOR = VAL_LOSS
EARLY_STOPPING_MIN_DELTA = 1e-4
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_VERBOSE = VERBOSE
EARLY_STOPPING_MODE = MIN
EARLY_STOPPING_RESTORE_BEST_WEIGHTS = False

# ...
START_TOKEN = "[START]"
END_TOKEN = "[END]"

# Vocab min freq
MIN_FREQ = 3